name: quantecon
channels:
  - default
  - conda-forge
dependencies:
  - python=3.13
  - anaconda=2025.06
  - pip
  - pip:
    - jupyter-book==1.0.4post1
    - quantecon-book-theme==0.9.2
    - sphinx-tojupyter==0.3.1
    - sphinxext-rediraffe==0.2.7
    - sphinx_reredirects==0.1.4
    - sphinx-exercise==1.0.1
    - git+https://github.com/executablebooks/sphinx-proof.git@main
    - ghp-import==1.1.0
    - sphinxcontrib-youtube==1.4.1 #Version 1.3.0 is required as quantecon-book-theme is only compatible with sphinx<=5
    - sphinx-togglebutton==0.3.2
    - --index-url https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple